name: segformer-b2
img_size: 512
in_chals: 3
num_classes: 150
embed_dims: [64, 128, 320, 512]
num_heads: [1, 2, 5, 8]
mlp_ratios: [4, 4, 4, 4]
qkv_bias: true
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1
depths: [3, 4, 6, 3]
sr_ratios: [8, 4, 2, 1]
decoder_dim: 768
decoder_drop_rate: 0.1
